sudo: false
language: node_js
script:
  - "npm run build && npm test"
after_script:
  - "istanbul cover --verbose --dir coverage node_modules/.bin/_mocha scripts/parse-emoji-data.js -- -u exports -R spec && cat coverage/lcov.info | coveralls; rm -rf coverage/lcov*"
